// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: packages.sql

package data

import (
	"context"
	"database/sql"
)

const addPackageWithVersion = `-- name: AddPackageWithVersion :one
INSERT into packages (name, url, version) VALUES (
	?, ?, ?
	) RETURNING id, name, url, version, created_at, updated_at
`

type AddPackageWithVersionParams struct {
	Name    string
	Url     string
	Version sql.NullString
}

func (q *Queries) AddPackageWithVersion(ctx context.Context, arg AddPackageWithVersionParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, addPackageWithVersion, arg.Name, arg.Url, arg.Version)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addPackageWithoutVersion = `-- name: AddPackageWithoutVersion :one
INSERT into packages (
	name, url
)
VALUES (
	?, ?
) RETURNING id, name, url, version, created_at, updated_at
`

type AddPackageWithoutVersionParams struct {
	Name string
	Url  string
}

func (q *Queries) AddPackageWithoutVersion(ctx context.Context, arg AddPackageWithoutVersionParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, addPackageWithoutVersion, arg.Name, arg.Url)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIDByName = `-- name: GetIDByName :one
select id from packages where name = ?
`

func (q *Queries) GetIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPackageByName = `-- name: GetPackageByName :one
select id, name, url, version, created_at, updated_at from packages where name = ?
`

func (q *Queries) GetPackageByName(ctx context.Context, name string) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackageByName, name)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPackageURLByName = `-- name: GetPackageURLByName :one
select url from packages where name = ?
`

func (q *Queries) GetPackageURLByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPackageURLByName, name)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getPackgeByID = `-- name: GetPackgeByID :one
select id, name, url, version, created_at, updated_at from packages where id = ?
`

func (q *Queries) GetPackgeByID(ctx context.Context, id int64) (Package, error) {
	row := q.db.QueryRowContext(ctx, getPackgeByID, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages
set name = ?, url = ?, version = ?
where id = ?
RETURNING id, name, url, version, created_at, updated_at
`

type UpdatePackageParams struct {
	Name    string
	Url     string
	Version sql.NullString
	ID      int64
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRowContext(ctx, updatePackage,
		arg.Name,
		arg.Url,
		arg.Version,
		arg.ID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
