// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups_packages.sql

package data

import (
	"context"
	"strings"
)

const assignPackageToGroup = `-- name: AssignPackageToGroup :exec
INSERT OR IGNORE INTO group_packages (group_id, package_id)
VALUES (?, ?)
`

type AssignPackageToGroupParams struct {
	GroupID   int64
	PackageID int64
}

func (q *Queries) AssignPackageToGroup(ctx context.Context, arg AssignPackageToGroupParams) error {
	_, err := q.db.ExecContext(ctx, assignPackageToGroup, arg.GroupID, arg.PackageID)
	return err
}

const getGroupIDByName = `-- name: GetGroupIDByName :one
SELECT id FROM groups WHERE name = ?
`

func (q *Queries) GetGroupIDByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getGroupIDByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPackageIDsByURLs = `-- name: GetPackageIDsByURLs :many
SELECT id FROM packages
WHERE url IN (/*SLICE:urls*/?)
`

func (q *Queries) GetPackageIDsByURLs(ctx context.Context, urls []string) ([]int64, error) {
	query := getPackageIDsByURLs
	var queryParams []interface{}
	if len(urls) > 0 {
		for _, v := range urls {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:urls*/?", strings.Repeat(",?", len(urls))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:urls*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackagesByGroup = `-- name: ListPackagesByGroup :many
SELECT p.id, p.name, p.url, p.version, p.freq, p.created_at, p.updated_at, p.last_used, p.is_deleted
FROM packages p
JOIN group_packages gp ON gp.package_id = p.id
JOIN groups g ON g.id = gp.group_id
WHERE g.name = ? and p.is_deleted = false
ORDER BY p.name ASC
`

func (q *Queries) ListPackagesByGroup(ctx context.Context, name string) ([]Package, error) {
	rows, err := q.db.QueryContext(ctx, listPackagesByGroup, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Version,
			&i.Freq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsed,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePackagesFromGroup = `-- name: RemovePackagesFromGroup :exec
DELETE FROM group_packages
WHERE group_id = ?
AND package_id IN (/*SLICE:package_ids*/?)
`

type RemovePackagesFromGroupParams struct {
	GroupID    int64
	PackageIds []int64
}

func (q *Queries) RemovePackagesFromGroup(ctx context.Context, arg RemovePackagesFromGroupParams) error {
	query := removePackagesFromGroup
	var queryParams []interface{}
	queryParams = append(queryParams, arg.GroupID)
	if len(arg.PackageIds) > 0 {
		for _, v := range arg.PackageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:package_ids*/?", strings.Repeat(",?", len(arg.PackageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:package_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}
