// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"database/sql"
)

type Group struct {
	ID        int64
	Name      string
	IsDeleted sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type GroupPackage struct {
	GroupID   int64
	PackageID int64
}

type Package struct {
	ID        int64
	Name      string
	Url       string
	Version   sql.NullString
	Freq      sql.NullInt64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	LastUsed  sql.NullTime
	IsDeleted sql.NullInt64
}
