// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"database/sql"
)

type Package struct {
	ID        int64
	Name      string
	Url       string
	Version   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
